{
 "title": "State server for alerts",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "HV", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Disk Use",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - (sum(wmi_logical_disk_free_bytes{instance=~\"192.168.58.55:9182\",volume=~\"C:\"}) / sum(wmi_logical_disk_size_bytes{instance=~\"192.168.58.55:9182\",volume=~\"C:\"})) ",
     "legendFormat": "Disk C 58.55"
    },
    {
     "expr": "1 - (sum(wmi_logical_disk_free_bytes{instance=~\"192.168.58.35:9182\",volume=~\"C:\"}) / sum(wmi_logical_disk_size_bytes{instance=~\"192.168.58.35:9182\",volume=~\"C:\"})) ",
     "legendFormat": "Disk C 58.35"
    },
    {
     "expr": "1 - (sum(wmi_logical_disk_free_bytes{instance=~\"192.168.58.45:9182\",volume=~\"C:\"}) / sum(wmi_logical_disk_size_bytes{instance=~\"192.168.58.45:9182\",volume=~\"C:\"})) ",
     "legendFormat": "Disk C 58.45"
    },
    {
     "expr": "1 - (sum(wmi_logical_disk_free_bytes{instance=~\"192.168.58.30:9182\",volume=~\"C:\"}) / sum(wmi_logical_disk_size_bytes{instance=~\"192.168.58.30:9182\",volume=~\"C:\"})) ",
     "legendFormat": "Disk C 58.30"
    },
    {
     "expr": "1 - (sum(wmi_logical_disk_free_bytes{instance=~\"192.168.58.20:9182\",volume=~\"C:\"}) / sum(wmi_logical_disk_size_bytes{instance=~\"192.168.58.20:9182\",volume=~\"C:\"})) ",
     "legendFormat": "Disk C 58.20"
    },
    {
     "expr": "1 - (sum(wmi_logical_disk_free_bytes{instance=~\"10.10.160.2:9182\",volume=~\"C:\"}) / sum(wmi_logical_disk_size_bytes{instance=~\"10.10.160.2:9182\",volume=~\"C:\"})) ",
     "legendFormat": "Disk C 160.2"
    },
    {
     "expr": "1 - (sum(wmi_logical_disk_free_bytes{instance=~\"192.168.58.55:9182\",volume=~\"D:\"}) / sum(wmi_logical_disk_size_bytes{instance=~\"192.168.58.55:9182\",volume=~\"D:\"})) ",
     "legendFormat": "Disk D 58.55"
    },
    {
     "expr": "1 - (sum(wmi_logical_disk_free_bytes{instance=~\"192.168.58.35:9182\",volume=~\"D:\"}) / sum(wmi_logical_disk_size_bytes{instance=~\"192.168.58.35:9182\",volume=~\"D:\"})) ",
     "legendFormat": "Disk D 58.35"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "((wmi_cs_physical_memory_bytes{instance=~\"192.168.58.55:9182\"} - wmi_os_physical_memory_free_bytes{instance=~\"192.168.58.55:9182\"}) * 100)/ wmi_cs_physical_memory_bytes{instance=~\"192.168.58.55:9182\"}",
     "legendFormat": "Memory Load 58.55"
    },
    {
     "expr": "((wmi_cs_physical_memory_bytes{instance=~\"192.168.58.35:9182\"} - wmi_os_physical_memory_free_bytes{instance=~\"192.168.58.35:9182\"}) * 100)/ wmi_cs_physical_memory_bytes{instance=~\"192.168.58.35:9182\"}",
     "legendFormat": "Memory Load 58.35"
    },
    {
     "expr": "((wmi_cs_physical_memory_bytes{instance=~\"192.168.58.45:9182\"} - wmi_os_physical_memory_free_bytes{instance=~\"192.168.58.45:9182\"}) * 100)/ wmi_cs_physical_memory_bytes{instance=~\"192.168.58.45:9182\"}",
     "legendFormat": "Memory Load 58.45"
    },
    {
     "expr": "((wmi_cs_physical_memory_bytes{instance=~\"192.168.58.30:9182\"} - wmi_os_physical_memory_free_bytes{instance=~\"192.168.58.30:9182\"}) * 100)/ wmi_cs_physical_memory_bytes{instance=~\"192.168.58.30:9182\"}",
     "legendFormat": "Memory Load 58.30"
    },
    {
     "expr": "((wmi_cs_physical_memory_bytes{instance=~\"192.168.58.20:9182\"} - wmi_os_physical_memory_free_bytes{instance=~\"192.168.58.20:9182\"}) * 100)/ wmi_cs_physical_memory_bytes{instance=~\"192.168.58.20:9182\"}",
     "legendFormat": "Memory Load 58.20"
    },
    {
     "expr": "((wmi_cs_physical_memory_bytes{instance=~\"10.10.158.2:9182\"} - wmi_os_physical_memory_free_bytes{instance=~\"10.10.158.2:9182\"}) * 100)/ wmi_cs_physical_memory_bytes{instance=~\"10.10.158.2:9182\"}",
     "legendFormat": "Memory Load 158.2"
    },
    {
     "expr": "((wmi_cs_physical_memory_bytes{instance=~\"10.10.160.2:9182\"} - wmi_os_physical_memory_free_bytes{instance=~\"10.10.160.2:9182\"}) * 100)/ wmi_cs_physical_memory_bytes{instance=~\"10.10.160.2:9182\"}",
     "legendFormat": "Memory Load 160.2"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "1 - avg(irate(wmi_cpu_time_total{instance=~\"192.168.58.55:9182\",mode=\"idle\"}[5m])) > 0",
     "legendFormat": "CPU 58.55"
    },
    {
     "expr": "1 - avg(irate(wmi_cpu_time_total{instance=~\"192.168.58.35:9182\",mode=\"idle\"}[5m])) > 0",
     "legendFormat": "CPU 58.35"
    },
    {
     "expr": "1 - avg(irate(wmi_cpu_time_total{instance=~\"192.168.58.45:9182\",mode=\"idle\"}[5m])) > 0",
     "legendFormat": "CPU 58.45"
    },
    {
     "expr": "1 - avg(irate(wmi_cpu_time_total{instance=~\"192.168.58.30:9182\",mode=\"idle\"}[5m])) > 0",
     "legendFormat": "CPU 58.30"
    },
    {
     "expr": "1 - avg(irate(wmi_cpu_time_total{instance=~\"192.168.58.20:9182\",mode=\"idle\"}[5m])) > 0",
     "legendFormat": "CPU 58.20"
    },
    {
     "expr": "1 - avg(irate(wmi_cpu_time_total{instance=~\"10.10.158.2:9182\",mode=\"idle\"}[5m])) > 0",
     "legendFormat": "CPU 158.2"
    },
    {
     "expr": "1 - avg(irate(wmi_cpu_time_total{instance=~\"10.10.160.2:9182\",mode=\"idle\"}[5m])) > 0",
     "legendFormat": "CPU 160.2"
    }
   ]
  },
  {
   "title": "UP state HV",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "up{instance=\"192.168.58.55:9182\"}",
     "legendFormat": "Status 58.55"
    },
    {
     "expr": "up{instance=\"192.168.58.35:9182\"}",
     "legendFormat": "Status 58.35"
    },
    {
     "expr": "up{instance=\"192.168.58.45:9182\"}",
     "legendFormat": "Status 58.45"
    },
    {
     "expr": "up{instance=\"192.168.58.30:9182\"}",
     "legendFormat": "Status 58.30"
    },
    {
     "expr": "up{instance=\"192.168.58.20:9182\"}",
     "legendFormat": "Status 58.20"
    },
    {
     "expr": "up{instance=\"10.10.158.2:9182\"}",
     "legendFormat": "Status 158.2"
    },
    {
     "expr": "up{instance=\"10.10.160.2:9182\"}",
     "legendFormat": "Status 160.2"
    }
   ]
  },
  { "title": "UPS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "UPS Server input voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    {
     "expr": "ups_input_voltage{name=\"USB/ON-LINE_R420F5J00024\"}",
     "legendFormat": "UPS2(Нижний)"
    },
    {
     "expr": "ups_input_voltage{name=\"USB/ON-LINE_R420G9V00075\"}",
     "legendFormat": "UPS1(Верхний)"
    }
   ]
  },
  {
   "title": "UPS Server output voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "ups_output_voltage", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "UPS Temp",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "ups_temp{name=\"USB/ON-LINE_R420F5J00024\"}",
     "legendFormat": "UPS2(Нижний)"
    },
    {
     "expr": "ups_temp{name=\"USB/ON-LINE_R420G9V00075\"}",
     "legendFormat": "UPS1(Верхний)"
    }
   ]
  },
  {
   "title": "Battery voltage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "ups_battery_voltage", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "UPS Time remaining",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "yaxes": [
    { "format": "dtdurations" }
   ],
   "targets": [
    { "expr": "ups_battery_time_remaining", "legendFormat": "{{name}}" }
   ]
  },
  {
   "title": "UPS Battery capasity",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "ups_battery_capacity", "legendFormat": "{{name}}" }
   ]
  },
  { "title": "AD", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } }
 ]
}